spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
  profiles:
    active: ${ENV:local}
  redis:
    timeout: PT5S
    jedis:
      pool:
        max-idle: 30
        min-idle: 5
        max-wait: PT10S
        max-active: 8
    host: 127.0.0.1
    port: 6379


logging:
  file: ./logback.log
server:
  port: 8888